config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'checkout', to: "billing#show"

  get 'checkout', to: "checkouts#show"
  get 'billing', to: "billing#show"


  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :projects do
    resources :comments, module: :projects
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  post "checkouts/show", to: "checkouts#show", as: "checkouts_show"
  get "success", to: "checkouts#success"
  get "cancel", to: "checkouts#cancel"

  resources :webhooks, only: [:create]

  # post "projects/add_to_cart/:id", to: "projects#add_to_cart", as: "add_to_cart"
  # delete "projects/remove_from_cart/:id", to: "projects#remove_from_cart", as: "remove_from_cart"

  post "projects/add_to_cart/:id", to: "shoppingcart#add_to_cart", as: "add_to_cart"
  delete "projects/remove_from_cart/:id", to: "shoppingcart#remove_from_cart", as: "remove_from_cart"
  get "checkout/cart", to: "shoppingcart#show", as: "shoppingcart"

  get "search", to: "projects#search"

  resource :subscription

  # resource :categories
  resources :categories

  root to: 'projects#index'
end

app/models/project.rb
class Project < ApplicationRecord
  # searchkick word_middle: [:title, :status]
  # searchkick
  belongs_to :user
  has_rich_text :description
  has_one_attached :thumbnail
  has_many :comments, as: :commentable


  has_many :categories_projects
  has_many :categories, through: :categories_projects


  # has_many :perks, dependent: :destroy
  # accepts_nested_attributes_for :perks, allow_destroy: true, reject_if: proc { |attr| attr['title'].blank? }
  after_update :create_and_assign_new_stripe_price, if: :saved_change_to_price?

  scope :active, ->{ where(status: "active") }
  scope :inactive, ->{ where(status: "inactive") }

  monetize :price, as: :price_cents

  paginates_per 3

  after_create do
    project = Stripe::Product.create(name: self.title)
    price = Stripe::Price.create(product: project.id, unit_amount: self.price.to_i, currency: self.currency)
    update(stripe_product_id: project.id, stripe_price_id: price.id)
  end

  def backers
    # find users who backed a specific project
  end

  def active?
    status == "active"
  end

  def inactive
    status == "inactive"
  end

  def to_builder
    Jbuilder.new do |product|
      product.price stripe_price_id
      product.quantity 1
    end
  end

  def create_and_assign_new_stripe_price
    price = Stripe::Price.create(product: self.stripe_product_id, unit_amount: self.price.to_i, currency: self.currency)
    update(stripe_price_id: price.id)
  end

  def self.search(params)  # need to uncomment this method to use elasticsearch
    # where("LOWER(title) LIKE?", "%#{params}%")
    
    projects = []
    projects << Project.left_joins(:comments).where("LOWER(projects.title) LIKE :query OR LOWER(projects.status) LIKE :query OR LOWER(comments.body) LIKE :query", query: "%#{params}%".downcase)

    projects << Project.where(id: ActionText::RichText.all.where("body LIKE ?", "%#{params}%".downcase).pluck(:record_id))

    return Project.where(id: ((projects[0] | projects[1]).pluck(:id)))

    # Nokogiri::HTML(Project.find(36).description.body.to_s).text.strip
    # ActionController::Base.helpers.strip_tags(Project.last.description.body.to_s).strip
    # Project.last.description.to_plain_text
    # Project.with_rich_text_description
  end


  # # for searchkick
  # def search_data
  #   {
  #     title: title,
  #     status: status
  #   }
  # end


  ################ Active Admin ###################

  def self.ransackable_scopes(_auth_object = nil)
    %i(category_eq thumbnail_eq comment_contains comment_equals comment_starts_with comment_ends_with description_contains)
  end

  def self.description_contains(value)
    where(id: ActionText::RichText.all.where("LOWER(body) LIKE ?", "%#{value}%".downcase).pluck(:record_id))
  end

  def self.thumbnail_eq(value)
    # ActiveStorage::Blob.all.where("filename LIKE ?", "%#{value}%")
    project_list = []
    self.all.each do |project|
      if project.thumbnail.present? && project.thumbnail_blob.filename == value
        project_list << project
      end
    end
    where(id: project_list.pluck(:id))
  end

  def self.category_eq(value)
    where(id: CategoriesProject.where(category_id: Category.where("LOWER(name) LIKE ?", "%#{value}%".downcase).pluck(:id)).pluck(:project_id))
  end

  def self.comment_contains(value)
    # where(id: Comment.where("body LIKE ?", "%#{value}%").pluck(:commentable_id))
    joins(:comments).where('LOWER(comments.body)  LIKE ?', "%#{value}%".downcase)
  end

  ################ Active Admin ###################

end

app/controllers/projects/comments_controller.rb
class Projects::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Project.find(params[:project_id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :add_to_cart, :remove_from_cart]

  # before_action :force_json, only: :search

  # GET /projects or /projects.json
  def index
    @titles = Project.pluck(:title)
    @projects = Project.page params[:page]
    # @query = params[:q] ||= ""
    # @projects = Project.where("title LIKE?", "%#{@query}%").page params[:page]

    respond_to do |format|
      format.html
      # format.json  { render :json => @projects }
      # format.js { render 'index.js.erb' }
      format.js
      # format.json{ render json: @titles}
    end
  end

  def search
    ############################## with elasticsearch-searckick ############################

    # @query = params[:q] ||= ""
    # project_ids = []

    # #@projects = Project.search(@query, fields: ["title^4", "status"], match: :word_middle, page: params[:page], per_page: 3, misspellings: {edit_distance: 3})
    
    # # @results = Searchkick.search(@query, match: :word_middle, misspellings: {edit_distance: 3}, models: [Project, Comment])

    # @results = Searchkick.search(@query, fields: ["title", "status", "body"], match: :word_middle, misspellings: {edit_distance: 3}, models: [Project, Comment])

    # @results.hits.each_with_index do |result, idx|
    #   if result["_index"].include? "comment"
    #     project_ids << Project.find(Comment.find(result["_id"]).commentable_id).id
    #   else
    #     project_ids << Project.find(result["_id"]).id
    #   end
    # end

    # project_ids << ActionText::RichText.all.where("body LIKE ?", "%#{@query}%".downcase).pluck(:record_id)

    # @projects = Project.where(id: project_ids.flatten).page params[:page]

    # # render "index"

    # respond_to do |format|
    #   format.html { render "index.html.erb"}
    #   format.js { render "search.js.erb" }
    # end

    ############################## without elasticsearch-searckick ############################

    # if params[:q].blank?
    #   @projects = Project.page params[:page]
    # else
    #   @query = params[:q]
    #   # @projects = Project.search(params[:q]).page params[:page]  # we can write the logic in Project model itself
    #   # @projects = Project.where("title LIKE?", "%" + params[:q] + "%")
    #   @projects = Project.where("LOWER(title) LIKE?", "%#{@query}%".downcase).page params[:page]
    # end

    # @projects = Project.where("LOWER(title) LIKE?", "%#{@query}%".downcase).page params[:page]

    @query = params[:q] ||= ""
    @projects = Project.search(params[:q]).page params[:page]  # we can write the logic in Project model itself

    # render "index"
    # render json: {project_titles: @projects.pluck(:title)}
    # @project_choices = Project.search(params[:q]).order(:title).limit(5)
    @project_choices = Project.where("LOWER(title) LIKE?", "%#{@query}%".downcase).order(:title).limit(5)
    
    respond_to do |format|
      format.js   { render :search }
      format.html { render :index }
      # format.json {@project_titles = @projects.pluck(:title)}
      format.json{ render json: @project_choices}
    end

  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        ExpireProjectJob.set(wait_until: @project.expires_at).perform_later(@project)
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id]) if params[:id] != "shoppingcart"
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :price, :price_cents, :currency, :donation_goal, :description, :thumbnail, :category_ids=>[])
    end

    # def force_json
    #   request.format = :json
    # end

end

app/helpers/projects/comments_helper.rb
module Projects::CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_active_project.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white rounded-lg lg:p-10">
  <div class="flex flex-wrap items-center justify-between w-full pb-4 mb-8 border-b-2 border-gray-200">
    <div class="flex flex-wrap items-start justify-between w-full pb-4 mb-4 border-b-2 border-gray-200">
      <div class="flex-1">
        <h1 class="text-3xl font-bold leading-none text-gray-800"><%= project.title %></h1>
        <p class="text-sm italic text-gray-500">Created by <%= project.user.name ||=
      project.user.username %></p>
      </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%= number_to_currency(project.current_donation_amount) %>/mo</p>
      <p class="text-sm text-gray-500">pledged of <%= number_to_currency(project.donation_goal) %>/mo</p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%#= project.backings_count %></p>
      <p class="text-sm text-gray-500">backers</p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%= distance_of_time_in_words_to_now(project.expires_at) %></p>
      <p class="text-sm text-gray-500">to go</p>
    </div>
  </div>

  <div class="flex flex-wrap items-start justify-between w-full mb-6">
    <div class="w-full lg:w-3/5">
    <% if project.thumbnail.present? %>
      <%= image_tag project.thumbnail, class: "rounded" %>
    <% else %>
      <div class="flex items-center justify-center p-8 text-center bg-gray-100 rounded">
        <div class="">
          <p class="text-xs font-bold text-gray-600 uppercase">PROJECT</p>
          <h3 class="text-2xl text-black"><%= project.title %></h3>
        </div>
      </div>
    <% end %>
      <div class="my-6">
        <%= render "comments/comments", commentable: project  %>
        <%= render "comments/form", commentable: project %>
      </div>
    </div>

    <div class="w-full mt-6 lg:pl-10 lg:w-2/5 lg:mt-0">
      <div class="mb-6">
        <p class="text-sm font-semibold text-gray-500 uppercase break-words">Description</p>
        <%= project.description %>

        <%= project.price_cents %>
        <%#= button_to "Buy now!", checkouts_show_path, params: {id: project.id, mode: "payment"}, remote: true, data: { disable_with: "validating..."} %>
        
        <%#= render partial: "pay/stripe/checkout_button", locals: {session: @checkout_session, title: "Checkout"} %>
        <%#= link_to 'Billing Portal', @portal_session.url, class: "btn btn-sm btn-outlined btn-default" %>


        <% if @cart.include?(project) %>
          <%= button_to "Remove from cart", remove_from_cart_path(project), method: :delete, class: "btn btn-default inline-block text-center my-2 bg-yellow-500" %>
        <% else %>
          <%= button_to "Add to cart", add_to_cart_path(project), class: "btn btn-default inline-block text-center my-2 bg-yellow-500" %>
        <% end %>


      </div>
    </div>
  </div>

 <% if admin? || author_of(project) %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_project_path(project), class: "btn btn-sm btn-outlined btn-default" %>
      <%= link_to 'Delete', project_path(project), method: :delete, class: "btn btn-sm btn-outlined btn-default", data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, multipart: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="p-6 mb-5 text-red-500 bg-white rounded">
      <h2 class="font-bold text-red-500"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :thumbnail, "Project thumbnail", class: "label" %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="mb-6">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :categories, class: "label" %>
    <%= form.collection_select :category_ids, Category.order(:name), :id, :name, {}, {class: 'select2 w-full box-border bg-white border-solid border-2 border-gray-600 z-50', multiple: true}%>
  </div>

  <dev class="flex flex-row space-x-4">
    <div class="mb-6">
      <%= form.label :price, class: "label" %>
      <%= form.text_field :price_cents, class: "input" %>
    </div>

    <div class="mb-6">
      <%= form.label :currency, class: "label" %>
      <%= form.text_field :currency, class: "input" %>
    </div>
  </dev>

  <div class="mb-6">
    <%= form.label :donation_goal, class: "label" %>
    <%= form.text_field :donation_goal, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.rich_text_area :description, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.submit class: "btn btn-default"%>
  </div>
<% end %>


<script type="text/javascript">
  $('.select2').select2();
</script>

<style type="text/css">
  .select2-selection__choice__display{
    background-color: white;
    color: red;
  }
  .select2-results{
    background-color: blue;
    color: white;
  }
  /*.select2-results__options{
    background-color: blue;
    color: white;
  }*/
  /*.select2-results__option[aria-selected=true] { background-color: teal !important; }*/
  .select2-results__option[aria-selected=true]{
    background-color: #00BFFF !important;
  }
  .select2-results__option--selectable{
    background-color: blue;
    color: white;
  }
  .select2-results__option{
    background-color: rgba(30, 64, 175, var(--tw-bg-opacity));
    color: white;
  }
  .select2-results__option--highlighted{
    background-color: indigo;
    color: white;
  }
  .select2-selection__choice__display{
    background-color: rgba(30, 64, 175, var(--tw-bg-opacity));
    color: white;
  }
  .select2-search{
    background-color: white;
    color: white;
  }
  /*.select2-search--inline{
    background-color: blue;
    color: red;
  }*/
  .select2-results__option--selected{
    background-color: white;
    color: black;
  }
</style>

app/views/projects/_inactive_project.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white border-2 border-red-500 rounded-lg lg:p-10">
  <div class="flex flex-wrap items-center justify-between w-full pb-4 mb-8 border-b-2 border-gray-200">
    <div class="flex flex-wrap items-start justify-between w-full pb-4 mb-4 border-b-2 border-gray-200">
      <div class="flex-1">
        <span class="px-2 py-1 text-xs font-semibold text-white bg-red-500 rounded-lg">Inactive</span>

        <h1 class="mt-4 text-3xl font-bold leading-none text-gray-800"><%= project.title %></h1>
        <p class="text-sm italic text-gray-500">Created by <%= project.user.name ||=
      project.user.username %></p>
      </div>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%= number_to_currency(project.current_donation_amount) %> /mo</p>
      <p class="text-sm text-gray-500">pledged of <%= number_to_currency(project.donation_goal) %> /mo</p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none"><%#= project.backings_count %></p>
      <p class="text-sm text-gray-500">backers</p>
    </div>

    <div class="w-full mb-4 lg:w-1/5 lg:mb-0">
      <p class="m-0 text-xl font-semibold leading-none">Expired</p>
      <p class="text-sm text-gray-500"><%= time_ago_in_words(@project.expires_at) %> ago</p>
    </div>
  </div>

  <div class="flex flex-wrap items-start justify-between mb-6">
    <div class="w-full lg:w-3/5">
    <% if project.thumbnail.present? %>
      <%= image_tag project.thumbnail, class: "rounded" %>
    <% else %>
      <div class="flex items-center justify-center p-8 text-center bg-gray-100 rounded">
        <div class="">
          <p class="text-xs font-bold text-gray-600 uppercase">PROJECT</p>
          <h3 class="text-2xl text-black"><%= project.title %></h3>
        </div>
      </div>
    <% end %>
    <div class="my-6">
      <%= render "comments/comments", commentable: project  %>
      <p>Comments are closed for inactive projects</p>
    </div>
    </div>
    <div class="w-full mt-6 lg:pl-10 lg:w-2/5 lg:mt-0">
      <p class="text-sm font-semibold text-gray-500 uppercase">Description</p>
      <%= project.description %>
    </div>
  </div>

  <% if admin? || author_of(project) %>
    <div class="absolute top-0 right-0 mt-4 mr-4">
      <%= link_to 'Edit', edit_project_path(project), class: "btn btn-sm btn-outlined btn-default" %>
      <%= link_to 'Delete', project_path(project), method: :delete, class: "btn btn-sm btn-outlined btn-default", data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>

app/views/projects/_project.html.erb
<div class="relative w-full p-6 mb-6 border-2 border-blue-700 rounded-lg lg:w-1/4 lg:mr-8">
  <%= image_tag project.thumbnail, class: "rounded" if project.thumbnail.present? %>
  <h3 class="mb-2 text-2xl font-bold text-black"><%= project.title %></h3>
  <div class="my-1"><%= truncate(strip_tags(project.description.to_s), length: 140) %></div>
  <p>Donation goal: <%= project.donation_goal %></p>
  <p class="text-sm italic opacity-75">Created by: <%= project.user.name %> </p>
  <%= link_to "View project", project, class: "btn btn-default inline-block text-center my-2" %>
  <% if author_of(project) %>
  <div class="absolute top-0 right-0 mt-2 mr-2">
    <%= link_to edit_project_path(project) do %>
      <svg class="w-6 h-6 text-white opacity-75 fill-current" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>edit</title><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"></path></svg>
    <% end %>
  </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="max-w-lg m-auto">
	<h1 class="mb-6 text-3xl font-bold">Create a Project</h1>
    <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<div class="container relative p-6 mx-auto text-gray-900 bg-white rounded-lg lg:p-10">
    <div id="project-wrap" class="flex flex-wrap items-start justify-center">
      <% if @projects.blank? %>
        <div>
          <h1 class="text text-red-500 text-xl">No search results for "<%="#{@query}" %>"</h1>
        </div>
      <%else%>
        <% @projects.each do |project| %>
          <%= render 'project', project: project%>
        <% end %>
      <%end%>
    </div>
</div>

<div id="pagination-wrap" class="container relative p-6 text-white-900 rounded-lg lg:p-10 flex flex-wrap justify-center">
    <%#= paginate @projects, remote: true %>
    <%= paginate @projects %>
</div>

app/views/projects/index.js.erb
$("#project-wrap").html("<%= escape_javascript render(@projects) %>");
$("#pagination-wrap").html("<%= escape_javascript(paginate(@projects, remote: true)) %>");

app/views/projects/new.html.erb
<div class="max-w-lg m-auto border-4 border-blue-700 rounded-lg px-2 pt-6 -pb-12">
	<h1 class="mb-6 text-3xl font-bold">Create a Project</h1>
    <%= render 'form', project: @project %>
</div>

app/views/projects/search.js.erb
<%= render @projects %>

app/views/projects/show.html.erb
<% if @project.active? %>
  <%= render "active_project", project: @project %>
<% else %>
  <%= render "inactive_project", project: @project %>
<% end %>